#Используем базовый образ с Alpine Linux для минимального размера
ARG ALPINE_VERSION=3.21
#--------------------------------Image--------------------------------
FROM alpine:${ALPINE_VERSION}
RUN set -ex; \
apk update && apk add --no-cache bash openrc openresolv iproute2 libqrencode 

#Tun2Socks
RUN mkdir /opt/tun2socks/
COPY ./tun2socks/tun2socks-linux-amd64 /opt/tun2socks/tun2socks

#Xray core
RUN mkdir /opt/xray/
RUN mkdir /opt/xray/config/
COPY ./xray-core/Xray-linux-64 /opt/xray/xray

COPY ./start.sh /opt/start.sh
RUN chmod +x /opt/start.sh
RUN sed -i 's/\r//' /opt/start.sh

RUN sed -i 's/^tty/#tty/' /etc/inittab
ENTRYPOINT ["sh", "-c"]
CMD ["/bin/bash /opt/start.sh && /sbin/init"]

#https://github.com/XTLS/Xray-core
#https://github.com/xjasonlyu/tun2socks
